keras_core/layers/preprocessing/tf_data_layer.py, keras_core/random/seed_generator.py
Fixes #432 for `RandomBrightness` and `RandomContrast` preprocessing layer test failures on `tf_data` compatibility.
- Use SeedGenerator backend when converting increment value to tensor
- `TFDataLayer` should compare backend with environment backend when deciding to create seed specific to custom backend arg.
=> Use SeedGenerator backend when creating variable

keras_core/models/functional.py
If we don't specify the names in the input tensor, we get:
```python
ValueError: When providing `inputs` as a dict, all keys in the dict must match the names of
the corresponding tensors. Received key 'x1' mapping to value 
<KerasTensor shape=(None, 10), dtype=float32, name=keras_tensor_16> which has name
'keras_tensor_16'. Change the tensor name to 'x1' (via `Input(..., name='x1')`)
```
It works if we specify the names as suggested in the error.
=> Add names to the input tensor, small typo

keras_core/optimizers/adam.py, keras_core/optimizers/adamw.py
`beta_1_power` and `beta_2_power` are defined in the next lines, so they can be removed from the beginning of the method.
=> Remove unused variables // adam & adamw

keras_core/random/seed_generator.py
The `self.backend=keras_core.backend` does not work with `namex` since it should be `keras_core.src.backend` when released.
=> bug fix for seed generator

keras_core/mixed_precision/__init__.py, keras_core/mixed_precision/dtype_policy.py
Resolves https://github.com/keras-team/keras-core/issues/468
=> Export DTypePolicy as Policy for backward compat

keras_core/ops/core.py
Most of the py files have the functions defined in that module at top:
Example:
```python
"""
scatter
scatter_update
slice
slice_update
while_loop
stop_gradient
shape
cast
convert_to_tensor
convert_to_numpy
"""
```
Should they be removed?
=> Complete missing docstrings in keras-core/ops/core.py

examples/keras_io/tensorflow/vision/zero_dce.py
Port the keras-io example [Zero-DCE for low-light image enhancement](https://keras.io/examples/vision/zero_dce/) to `keras_core`.
`tf.keras` backwards compatibility check: https://github.com/keras-team/keras-core/issues/485
Colab Notebook: https://colab.research.google.com/drive/1GuumdRuh9wy_Eo_zzORFfG2iX8gGG58a?usp=sharing
=> Port zero-dce example to `keras-core`

keras_core/ops/math.py, keras_core/ops/nn.py
Updated `keras_core/ops/math.py` and `keras_core/ops/nn.py` with docstring.
Please do let me know if any changes are needed.
=> Updated math.py & nn.py with docstrings.

requirements-common.txt, requirements-cuda.txt, requirements.txt
Not totally sure if we should merge this now, or wait for tf 2.14, but figured I could put it up anyway so people could use it. With https://github.com/tensorflow/tensorflow/pull/59825 tf-nightly can be installed using cuda pip packages. Which means we can write a recipe for cross framework GPU support.
To install a local development version...
```shell
pip install -r requirements-cuda.txt
python pip_build.py --install
```
To install the official pip version...
```shell
pip install -r requirements-cuda.txt
pip install keras-core --no-deps
```
Note that `--no-deps` is required to avoid pulling in `tensorflow` and `tf-nightly` at the same time.
This should work in a clean python env, as long nvidia drivers are >= 520. No conda or cuda shenanigans required!
=> Add a requirements file for multi-backend cuda

keras_core/backend/config.py
By default, tensorflow will consume all available GPU memory: https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth
Say you are running on KERAS_BACKEND=jax, and jax and tf have both been configured with GPU suport:
- keras_core will always import and initialize tensorflow
- tensorflow will use all available GPU memory
- jax will attempt any GPU allocation and immediately fail
Note this does not happen in colab because colab automatically exports the environment variable:
`TF_FORCE_GPU_ALLOW_GROWTH=true`
From keras-core, we can attempt to work around it by limiting tensorflow GPU growth. Long term we should work around it by not importing tensorflow on jax and torch backends.
=> Stop tensorflow from eating all GPU memory

examples/keras_io/tensorflow/vision/mirnet.py
Port the keras-io example [Low-light image enhancement using MIRNet](https://keras.io/examples/vision/mirnet/) to `keras-core`.
Colab Notebook: https://colab.research.google.com/drive/1t6QVYvkQ08-CHF15zvaVGUYRJyQ0cOcd?usp=sharing
=> Port mirnet example to `keras-core`

keras_core/ops/image.py
PR adds the docstring for `keras_core.ops.image.resize`
=> Added docstring ops/image/resize

examples/keras_io/tensorflow/vision/shiftvit.py
Remove tensorflow_addons dependency
Fix imports
Update shape computation in `DropPath` to `shape = (tf.shape(x)[0],) + (1,) * (len(x.shape) - 1)`
Update loss computation metrics update in subclassed model
Linked Issue: #222
=> Converted to Keras Core: A Vision Transformer without Attention

keras_core/layers/layer.py
Clean up docstrings to clarify variables vs weights.
=> Clean up variable vs weight in base layer

keras_core/backend/torch/optimizers/torch_adam.py, keras_core/backend/torch/optimizers/torch_optimizer.py, keras_core/backend/torch/optimizers/torch_parallel_optimizer.py, keras_core/backend/torch/optimizers/torch_sgd.py, keras_core/ops/symbolic_arguments.py, keras_core/optimizers/adam_test.py
With the new implementation, the `numerical_test.py` passed.
=> Add Adam optimizer parallel implementation for torch backend

keras_core/metrics/iou_metrics.py, keras_core/metrics/metric.py, keras_core/metrics/metrics_utils.py, keras_core/metrics/regression_metrics.py
Resolves the following issues -
1. When `ops.broadcast_to`, requires the shape to be resolved via `ops.shape` and fails when used with tensor.shape attribute for TensorFlow backend.
2. When multiplying `sample_weight` with `y_true`, it needs to be cast to the target tensor.  Many times, `self.dtype` is None and for regression metrics like `R2Score`, `y_true` is a float and `sample_weight` is an int, causing type mismatch in TensorFlow backend.
3. Remove the dtype specification in `self.num_samples` in `R2Score` metric initialization.  Having the dtype specified in the init, causes the variable to be put in CPU, causing CPU / GPU error when assigning value in `update_state` method.
There is still couple of more issues with how `sample_weight` is used in `iou_metric` that needs to be …
=> Resolve shape via ops in broadcast_to operation

keras_core/backend/torch/optimizers/torch_nadam.py, keras_core/backend/torch/optimizers/torch_optimizer.py, keras_core/optimizers/nadam.py, keras_core/optimizers/nadam_test.py
Fixed a bug in Nadam.
`numerical_test` passed for TF, JAX, and Torch backends (need to set the `tf.keras` model to `run_eagerly=True` due to a bug in `tf.keras`).
=> Add Nadam for torch backend

keras_core/backend/torch/numpy.py, keras_core/metrics/reduction_metrics.py, keras_core/metrics/reduction_metrics_test.py, keras_core/ops/numpy_test.py
I'm still not sure what broke this, but it appeared to change with the 0.1.1 release.
Please help me check if the outputs here are what we would expect.
=> Fix multi-dimension sample weights passed to mean metrics

keras_core/initializers/random_initializers_test.py
Uses `convert_to_numpy(values)` API instead of `np.array(values)`, as it doesn't work in torch backend when the tensor is on GPU.
=> Fixes Torch-GPU Test failure on initializers/random_initializers_test.py

keras_core/utils/module_utils.py
Fixes #555 by only setting `_available` in the `try` block
=> Fix Module Utils `_available` attribute

keras_core/backend/torch/random.py, keras_core/random/seed_generator.py
As tested, there is no noticable overhead for the added conditions in the if statement.
It now can reproduce the same dropout with the same seed.
=> Add random seed support for torch dropout

keras_core/layers/preprocessing/random_translation.py, keras_core/layers/preprocessing/random_translation_test.py
Related to #481 
Tests all passed in my local env
=> Convert RandomTranslation to the backend-agnostic implementation

keras_core/ops/numpy.py
also updated the outputs of examples in amax
=> docString for numpy.amin

keras_core/backend/common/keras_tensor_test.py, keras_core/trainers/data_adapters/array_data_adapter_test.py
Allows users to not have `jax` or `torch` package unless they are using that specific backend.
=> Update Tests for specific backend imports

keras_core/ops/image.py, keras_core/ops/image_test.py
As discussed in #529, this pull request implements [tf.image.extract_patches](https://www.tensorflow.org/api_docs/python/tf/image/extract_patches)  in keras ops
=> implement patch extraction in ops

keras_core/backend/torch/numpy.py, keras_core/ops/numpy_test.py
Correct a slight inconsistency between Torch and the other backends in the handling of empty tensors for `max` and `min`:
- All backends but Torch follow the numpy behaviour, which is to throw an exception on empty tensor, except if the argument `initial` is passed. See screenshot 1, on JAX as an example.
- On backend Torch, it returns 0 for `max`, and it fails for `min`, irrespective of the argument `initial`. See screenshot 2 for `max`.
This PR aligns the behaviour of Torch backend on numpy (see screenshot 3). Also adds a test.
Screenshot 1 - JAX `max`
Screenshot 2 - Torch `max`, before PR
Screenshot 3 - Torch `max`, after PR
=> Backend consistency in handling of empty tensor in `min` and `max`

examples/keras_io/vision/image_classification_with_vision_transformer.py
Added a backend-agnostic port of the example [Image classification with Vision Transformer](https://keras.io/examples/vision/image_classification_with_vision_transformer/) that works with TF, Jax, and Torch backends. Based on the TF-compatible port originally contributed by @divyashreepathihalli as part of https://github.com/keras-team/keras-core/pull/388.
Linked Issue: https://github.com/keras-team/keras-core/issues/222
Colab: https://colab.research.google.com/drive/15djhD0aS5qqCbeUDAhhg_7R9uZCmdpJb?usp=sharing
=> Backend-agnostic port of Image classification with Vision Transformer

examples/keras_io/tensorflow/vision/cutmix.py, examples/keras_io/tensorflow/vision/mixup.py
Made [CutMix data augmentation for image classification](https://keras.io/examples/vision/cutmix/) and [MixUp augmentation for image classification](https://keras.io/examples/vision/mixup/) more backend agnostic. Suggested by @soumik12345. 
Attaching the notebooks below: 
* [Colab notebook for cutmix](https://colab.research.google.com/drive/1EwPk-5E38A5460RHbLOMo6HDZv5aOVwZ?usp=sharing)
* [Colab notebook for mixup](https://colab.research.google.com/drive/1In0SM1T1RctlM-JXVG3EBALmKuaWBR31?usp=sharing)
Now, In these two examples, only two methods from `tensorflow` are used except `tf.data` and `tf.image`: 
* `tf.random.gamma`
* `tf.clip_by_value`
*I am willing to implement these two making separate PR for each.*
@fchollet
=> More backend agnostic in cutmix and mixup file

pip_build.py
pip_build while create whl files in `/dist`, which aren't cleaned up by the script unless you do so manually.
The script would install the first `.whl` it saw in `/dist`, which means if you have been building multiple versions of keras-core, the install script might grab the wrong one.
This makes sure to always grab the correct versioned `.whl`. Alternately we could clear the `/dist` dir each time we build.
=> Always install the correct version with pip_build

examples/keras_io/tensorflow/nlp/pretrained_word_embeddings.py
convert Keras IO [Using pre-trained word embeddings](https://keras.io/examples/nlp/pretrained_word_embeddings) example.
1. replace tensorflow.keras with keras_core
2. don't import tensorflow, only tf.data is used
3. keras_core.initializers.Constant only accepts scalar. use Embedding.set_weights() to initialized weights
Because tf_data is used by the vectorizer, the end-to-end model in the end of the script is not backend-agnostic.
diff: 79686c3
colab [notebook](https://colab.research.google.com/drive/1AVouUHGzCTg0nsaiq_HN6U4t5fPtvAHb?usp=sharing)
=> Convert pretrained word embeddings to Keras Core

examples/keras_io/vision/gradient_centralization.py
While trying to port [Gradient Centralization Example](https://keras.io/examples/vision/gradient_centralization/), 
It is working with `tensorflow` backend but facing issue usin tfds with `jax` and `torch`. In the [transfer learning guide](https://github.com/keras-team/keras-core/blob/main/guides/transfer_learning.py), it shows, I don't need to do anything with these datasets.
Here's the [Colab Notebook](https://colab.research.google.com/drive/1M2mH-g99r922KArTrL_acKRWmT84v_Gv?usp=sharing)
CC: @fchollet
=> port gcam backend agnostic

keras_core/backend/tensorflow/trainer.py
I'm not sure if support for TensorFlow older versions is intended, but it would be nice to take care of backward compatability because not everyone uses the latest TensorFlow. The current `TensorFlowTrainer` uses `tf.function` with the parameter `reduce_retracing` (e.g., [here](https://github.com/keras-team/keras-core/blob/main/keras_core/backend/tensorflow/trainer.py#L105)), but the `reduce_retracing` has been introduced since TF 2.9. This PR is able to handle this issue with adaptive keyword arguments.
- TF 2.8 docs: https://www.tensorflow.org/versions/r2.8/api_docs/python/tf/function
- TF 2.9 docs: https://www.tensorflow.org/versions/r2.9/api_docs/python/tf/function
=> Improve `TensorFlowTrainer` compatibility for TF<2.9

keras_core/backend/torch/image.py, keras_core/layers/preprocessing/random_translation.py, keras_core/layers/preprocessing/random_translation_test.py, keras_core/layers/preprocessing/random_zoom.py, keras_core/layers/preprocessing/random_zoom_test.py, keras_core/ops/image.py, keras_core/ops/image_test.py
Related to #481 
EDITED:
please see https://github.com/keras-team/keras-core/pull/574#issuecomment-1648995459
=====OLD=====
Expected output in correctness tests with torch backend has changed. The root cause might come from the inconsistency of the interpolation.
```bash
[[ 6.  7.  7.  8.  8.]
[11. 12. 12. 13. 13.]
[11. 12. 12. 13. 13.]
[16. 17. 17. 18. 18.]
[16. 17. 17. 18. 18.]]
tensor([[ 6.,  6.,  7.,  7.,  8.],
[ 6.,  6.,  7.,  7.,  8.],
[11., 11., 12., 12., 13.],
[11., 11., 12., 12., 13.],
[16., 16., 17., 17., 18.]])
[[ 0.  0.  0.  0.  0.]
[ 0.  5.  7.  9.  0.]
[ 0. 10. 12. 14.  0.]
[ 0. 20. 22. 24.  0.]
[ 0.  0.  0.  0.  0.]]
tensor([[ 0.,  0.,  0.,  0.,  0.],
[ 0.,  6.,  7.,  9.,  0.],
[ 0., 11., 12., 14.,  0.],
[ 0., 21., 22., 24.,  0.],
[ 0.,  0.,  0.,  0.,  0.]])
```
=> Convert RandomZoom to backend-agnostic and improve `affine_transform`

keras_core/trainers/trainer.py
Fixes #611.  Allows setting `jit_compile` on Model or in `model.compile` only if model supports it.  This prevents `LSTM`, `GRU` in TF backend from being run with `jit_compile` even if the user tries to override it in `model.compile`.
=> Set Jit compile only if Model supports it

keras_core/ops/numpy.py
Add more docstrings to functions in ops.numpy.
Covers all remaining functions starting with "a":
- append
- arange
- arccos
- arcsin
- arctan
- arctan2
- argmax
- argmin
- argsort
- array
- average
I largely copied the docs from numpy, adapting them when the arguments differed.
=> Add docstrings in numpy

requirements-common.txt, requirements.txt
Explicitly add `numpy`, `scipy` dependency and also set the minimum TF Version supported.
Pre-processing layers of `random_brightness` and other preprocessing layer tests fail in TF 2.12.  They are not caught in CI since CI installs latest Tensorflow (2.13).
This only fails for other backends (Jax / Torch), not for TF itself.
```
KERAS_BACKEND=torch pytest keras_core/layers/preprocessing/random_brightness_test.py
```
Fails on `RandomBrightnessTest::tf_data_compatibility` when used with TF 2.12
=> Set min TF Version

guides/making_new_layers_and_models_via_subclassing.py
Fix minor typo in `making_new_layers_and_models_via_subclassing.py`.
=> Typo in layer tutorial

keras_core/layers/layer.py
Silly bug, our mask call args look like `xx_mask` not `mask_xx`, we had the order flipped.
=> Only ignore xx_mask arguments for the build shapes dict

keras_core/backend/numpy/trainer.py, keras_core/backend/tensorflow/trainer.py, keras_core/trainers/trainer_test.py
related to #481 
This PR mainly implements the numpy trainer with references to torch and jax.
Two tests have been added to improve the test coverage of the numpy trainer:
- `test_steps_per_execution_steps_count_without_training`
- `test_on_batch_methods_without_training`
```bash
Name                                   Stmts   Miss  Cover
----------------------------------------------------------
keras_core/backend/numpy/trainer.py      142      5    96%
```
Additionally, there is a bug that some `steps_per_execution` are missing in `TFEpochIterator` declaration in `keras_core/backend/tensorflow/trainer.py`. It has been catched by new tests and fixed by this PR.
=> Add numpy trainer

keras_core/utils/dataset_utils.py, keras_core/utils/dataset_utils_test.py
Hi Team, 
This PR made following changes to following functions
- moving `keras` data-utils for split_dataset  from [here](https://github.com/keras-team/keras/blob/v2.13.1/keras/utils/dataset_utils.py) making sure all the settings stay's intact.
- need to rewrite following functions since all of them accept `tf.Dataset` and we need to support `torch` and `Jax`.
-  `split_dataset`
-  `_convert_dataset_to_list` 
- `_get_data_iterator_from_dataset`
- `_get_next_sample` 
- `_get_type_spec` 
- `_get_next_sample` 
- `_rescale_dataset_split_sizes` 
- `_restore_dataset_from_list`
=> [split_dataset] migrating from tf.keras to keras_core

guides/distributed_training_with_jax.py, guides/distributed_training_with_torch.py, keras_core/backend/jax/numpy.py, keras_core/backend/numpy/numpy.py, keras_core/backend/tensorflow/numpy.py, keras_core/backend/torch/numpy.py, keras_core/ops/nn.py, keras_core/ops/numpy.py, keras_core/ops/numpy_test.py
- Adds hyperbolic ops to ops/numpy
- Closes #612
=> Add hyperbolic ops

keras_core/layers/activations/elu_test.py, keras_core/layers/activations/prelu_test.py, keras_core/layers/pooling/global_average_pooling_test.py
Replaces `tf.keras` with numpy for expected outputs in Global Average Pooling and Elu/Prelu tests.
=> Removes ref in Global Average Pool and Elu/Prelu Activations

keras_core/ops/image.py, keras_core/ops/image_test.py
Two small fixes on `extract_patches`:
* Passing argument `size` as an int currently fails for symbolic tensor:
```
>>> x = KerasTensor([None, 20, 20, 3])
>>> keras_core.ops.image.extract_patches(x, size=5)
Traceback (most recent call last):
...
strides = (self.size[0], self.size[1])
TypeError: 'int' object is not subscriptable
```
Fixed and added unit-test.
* Examples in docstring are failing for me, I have to convert the arrays to "float32" beforehand.
```
>>> image = np.random.random((1, 20, 20, 3)) # batch of 2 RGB images
>>> patches = keras_core.ops.image.extract_patches(image, (5, 5))
Traceback (most recent call last):
...
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Conv2D as input #1(zero-based) was expected to be a double tensor but is a float …
```
=> Small fixes on `image.extract_patches`

keras_core/callbacks/learning_rate_scheduler.py, keras_core/callbacks/learning_rate_scheduler_test.py
**Description:**
This merge request updates the `learning_rate` type to `float` in the `learning_rate_scheduler`'s logs for the following reasons:
**Reason 1:**
Currently, when the `learning_rate` is not converted to floats, the history logs show that we are using the same parameter value, resulting in a display like this:
'learning_rate': [Parameter containing:
tensor(3.9063e-04),
Parameter containing:
tensor(3.9063e-04),
Parameter containing:
tensor(3.9063e-04),
...
Parameter containing:
tensor(3.9063e-04)]
This issue occurs we are keeping the parameter type throughout the epochs. Consequently, the parameter type remains the same, but its value changes dynamically as the training progresses. As a result, only the last value is visible, and we lose the history of the learning rate. …
=> Update learning_rate type to float in learning_rate_scheduler's logs

keras_core/backend/jax/numpy.py, keras_core/backend/numpy/numpy.py, keras_core/backend/tensorflow/numpy.py, keras_core/backend/torch/numpy.py, keras_core/ops/numpy.py, keras_core/ops/numpy_test.py
This op will help to implement `Discretization` layer.
The output of the op is unified to be like the tensorflow output. and there is somethings to consider:
1- jax and numpy can digitize if the bins are monotonically decreasing but torch and tensorflow can't. torch will return undefined output. And tensorflow will return an error.
2- jax, numpy, and torch has `right` arg but tensorflow hasn't. so I didn't add it
=> Add digitize op for Discretization layer

keras_core/layers/pooling/average_pooling_test.py, keras_core/layers/pooling/global_max_pooling_test.py, keras_core/layers/pooling/max_pooling_test.py
Replaces `tf.keras` with numpy expected results for pooling layers.
=> Removes `tf.keras` from Pooling tests - Max, Average and Global pooling

keras_core/ops/numpy.py
Related to #481.
Added a docstring to `keras_core.ops.bincount` / `keras_core.ops.numpy.bincount`.
=> Add numpy bincount docstrings

keras_core/backend/jax/math.py, keras_core/backend/numpy/math.py, keras_core/backend/tensorflow/math.py, keras_core/backend/torch/math.py, keras_core/ops/math.py, keras_core/ops/math_test.py
This op is a sibling of `segment_sum` which is useful in box decoding for a handful of 2D and 3D object detection models (and I would imagine instance segmentation models as well, although I have yet to encounter that particular use case)
=> Add a segment_max op

examples/keras_io/tensorflow/vision/mlp_image_classification.py
Port mlp_image_classification to keras_core.
This implementation works with Tensorflow, Torch, and JAX (at least on my machine).
<ins>A few points below</ins>:
**Reimplemented positional embedding**
Just like in (PR https://github.com/keras-team/keras-core/pull/602), I ran into the issue that the example wasn’t running with a Torch backend (I had the same cryptic error message: `RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.`).
To fix that, I had to re-implement the …
=> Port `mlp_image_classification.py` to all backends

keras_core/layers/preprocessing/random_flip.py, keras_core/layers/preprocessing/random_flip_test.py
I'm pretty sure that RandomFlip is jittable and `self.support_jit = False` should be removed.
This PR has added a test for this: `test_support_jit`
A script to test the jit functionality:
```python
import os
os.environ["KERAS_BACKEND"] = "tensorflow"  # "jax", "torch" and "numpy"
import numpy as np
import keras_core as keras
x = np.random.random(size=(2, 128, 128, 3)) * 255
layer = keras.layers.RandomFlip()
if keras.backend.backend() == "tensorflow":
import tensorflow as tf
@tf.function(jit_compile=True)
def get_output(x):
return layer.call(x)
elif keras.backend.backend() == "jax":
import jax
@jax.jit
def get_output(x):
return layer.call(x)
else:
def get_output(x):
return layer(x)
y = get_output(x)
print("succeed!")
```
=> Remove `self.support_jit = False` in RandomFlip

examples/keras_io/tensorflow/nlp/ner_transformers.py, keras_core/layers/attention/multi_head_attention.py
1. 489237f  breaks this example,  don't use tensor in MHA `__init__()`, ed2a726
2. keras.losses.Reduction.NONE  is no longer there, replace it with `None`
=> Make ner transformers work again

keras_core/activations/activations.py, keras_core/ops/nn.py
I added some missing docstrings to the activation functions.
=> Added some docstrings ops/nn.py

keras_core/backend/jax/numpy.py
Another spot we need this when passing a variable.
=> Convert to tensor for jax ops.numpy.transpose

keras_core/backend/jax/nn.py, keras_core/backend/tensorflow/nn.py, keras_core/backend/torch/nn.py, keras_core/ops/nn.py, keras_core/ops/nn_test.py
Essentially we are going to adopt the jax approach for softmax:
- The `axis` default is `-1` (aligns with tf/torch default behavior).
- Passing `axis=None` explicitly mean a reduction on all axes, which fits with jax and all numpy reduction ops.
This should be least surprising overall to users.
Also, let's `reshape` to get the `None` behavior we want in torch/tf, rather then compute the reduction ourselves, so we can be sure our numerics are the same close to zero.
=> Update the softmax default to axis=-1

keras_core/layers/preprocessing/random_flip.py, keras_core/layers/preprocessing/random_flip_test.py
Random Flip seems to fail for batched inputs.
For instance:
```
>>> (x_train, y_train), (x_test, y_test) = keras_core.datasets.cifar10.load_data()
>>> keras_core.layers.RandomFlip(mode="horizontal")(x_train[1]) # Works
>>> keras_core.layers.RandomFlip(mode="horizontal")(x_train) # Fails
InvalidArgumentError                      Traceback (most recent call last)
...
{{function_node __wrapped__SelectV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} condition [50000], then [50000,32,32,3], and else [50000,32,32,3] must be broadcastable [Op:SelectV2] name:
```
This is due to some shape broadcasting gone wrong, which this PR should fix. Added unit-test as well.
=> Random Flip for batched inputs

keras_core/ops/core.py
**Summary**
This fixes a small typo in the `WhileLoop` docstring in core.py
**Changes**
- In `WhileLoop` docstring, fix "implemetation" to "implementation"
**Location** 
https://github.com/keras-team/keras-core/blob/main/keras_core/ops/core.py#L233
**Note**: I know it's a very simple change :) , but this is my first pull request ever, and I am still learning how to use GitHub. I love this project; it's very future-proof. I am aiming to be a helpful and active contributor.
=> Fix typo in WhileLoop docstring in core.py

keras_core/ops/math.py
**Background**
The current implementation of the segment_max function in keras_core.ops.math has an error when dealing with symbolic tensors. Specifically, when checking for symbolic tensors and attempting to use the SegmentMax class's symbolic call method, it erroneously calls SegmentSum instead of SegmentMax.
**Changes**
Updated the segment_max function's symbolic tensor handling to call the correct SegmentMax class's symbolic_call method.
**Impact:**
Fixing this ensures that the segment_max function behaves correctly for symbolic tensors and avoids incorrect computations
=> Fix Issue in SegmentMax's Symbolic Call in keras_core/ops/math.py

keras_core/layers/convolutional/conv_test.py
Replaces `tf.keras` with numpy implementation for `conv1d` test.  Will do the same for Conv2D and Conv3D in a subsequent PR.
=> Replace `tf.keras` for expected result in Conv1D Test

keras_core/backend/tensorflow/core.py, keras_core/ops/core.py
This was already true in all contexts except when called on `tf.Tensor`s on the Tensorflow backend. In this case, we were returning a 1-D `tf.Tensor`.
This was leading to some weird incongruencies, e.g.
```python
ops.shape(np.ones((1, 2))) + (3,)
> (1, 2, 3)
ops.shape(np.ones((1, 2))) + (3,)
> tf.Tensor([4, 5])
```
=> Always return a tuple from ops.shape

keras_core/layers/normalization/layer_normalization.py, keras_core/layers/normalization/layer_normalization_test.py
Small think I just noticed, the `tf.keras` layernorm was using `tf.nn.moments` to compute mean and variance together.
However, we are computing them separately with numpy here, meaning that we were actually computing the mean of the inputs twice. Should be more efficient to reuse the computed mean to compute the variance.
=> Only compute mean once in layernorm

examples/keras_io/tensorflow/generative/cyclegan.py
1. colab [notebook](https://colab.research.google.com/drive/12Fiv90AdAk3u8igqZqs_pJ3lB0POeq2Y?usp=sharing)
2. keras to keras-core: the diff (565bdcb)
The CycleGan model has a custom tf-based `train_step()`, which its not backend-agnostic.
=> Convert cyclegan to keras-core

keras_core/layers/convolutional/conv_test.py, keras_core/layers/convolutional/conv_transpose_test.py, keras_core/utils/numerical_utils_test.py
* Replaces `tf.keras` with numpy reference implementation
* Adds test for `channel_first` and changing dilation rates.
* Replaces `tf.keras` in `numerical_utils_test.py`
=> Replace `tf.keras` with numpy  for conv2d and conv3d tests

keras_core/ops/function.py, keras_core/ops/math.py, keras_core/ops/nn.py
**Main Changes:**
1. Improved docstrings and added examples for segment_sum, segment_max, and rsqrt functions in keras_core/ops/math.py.
2. Added docstring for network_nodes in keras_core/ops/function.py 
3. Enhanced the docstring for multi_hot function in keras_core/ops/nn.py.
My target to add very easy to understand examples.
=> Enhanced Docstrings and Examples in /ops/function.py, /ops/math.py and /ops/nn.py.

keras_core/utils/summary_utils.py
This fixes two issues:
1. The original unique-ifying code did nothing. This is fixed.
2. The return values are now in bytes, consistent with the documentation and usage elsewhere in keras-core.
=> Fixed uniqueness bug and bits->bytes

examples/keras_io/tensorflow/generative/ddim.py, keras_core/layers/merging/concatenate.py
1. colab [notebook](https://colab.research.google.com/drive/1120anEh9Js9tPEPod-M3-w-x1UFcUZdS?usp=sharing) 
2. diff f98790b
- convert keras/tf.keras to keras_core
- replace most of tf ops except tf.image, tf.data, and tf.GrapdientTap
- fix ops.concat out of range issue
=> Convert ddim

keras_core/backend/jax/math.py, keras_core/backend/numpy/math.py, keras_core/backend/tensorflow/math.py, keras_core/backend/torch/math.py, keras_core/ops/math.py, keras_core/ops/math_test.py
Similar to #717 
This PR mainly implements `istft`. This allows us to reconstruct sequences from the frequency domain.
Notes: some clean up (e.g. `a` to `x`, `jax.numpy` to `jnp`) included, I can revert it if it is not necessary
```bash
ori. vs. lr RMSE: 3.663534e-09
ori. vs. np RMSE: 4.223074e-09
ori. vs. jax RMSE: 8.257622e-09
ori. vs. tf RMSE: 1.0522875e-08
ori. vs. torch RMSE: 8.910108e-09
```
Reconstructed results:
A standalone script:
(needs `pip install librosa matplotlib`)
```python
import jax
import librosa as lr
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from keras_core.backend.jax.math import istft as jax_istft
from keras_core.backend.numpy.math import istft as np_istft
from keras_core.backend.tensorflow.math import istft as tf_istft
from …
```
=> Add `irfft` and `istft`

keras_core/backend/torch/core.py
I attempted to incorporate MPS device and have already conducted testing across various models, datasets, and optimizers. However, I've encountered two current challenges:
1- There are certain performance issues present compared to CPU, even when excluding Keras Core from the equation, and using torch only
2- Some operators are not supported on MPS, and a temporary workaround involves setting PYTORCH_ENABLE_MPS_FALLBACK, though this does come at the cost of reduced speed.
=> An attempt to add MPS device to torch backend

keras_core/layers/convolutional/conv_test.py, keras_core/layers/convolutional/depthwise_conv_test.py, keras_core/layers/convolutional/separable_conv_test.py
* Removes `tf.keras` from Depthwise and Separable conv tests.
* Implemented separable conv as a combination of depthwise followed by regular conv with 1x1 kernel.  So imported the numpy test implementations for separable conv test.
Will send another PR to remove `tf.keras` from Transpose Conv test.
=> Remove `tf.keras` from depthwise and separable conv tests

keras_core/ops/numpy.py, keras_core/ops/numpy_test.py
**Bug Fix:**
In `shape_equal `function, using `axis=1` resulted in the `error: TypeError: 'int' object is not iterable.`
but  `axis=[1] `worked correctly.
After hours of trying  :)  the issue has been resolved, and now an integer, list, or tuple of integers  work as expected and documented.
**Improved Docstrings:**
The documentation for the shape_equal function has been enhanced. It now provides a more in-depth description and includes illustrative examples.
**Additional Tests:**
A new set of tests has been added to ensure the proper functionality of the `shape_equal `function.
Why do we need tests for the `shape_equal` function? Because there are 7 other functions depend on it:
1. Append ( )
2. Average ( )
3. Concatenate ( )
4. Hstack ( )
5. Stack ( )
6. Tensordot ( )
7. Vstack () …
=> Fix bug + Add Tests + Enhance docstrings (shape_equal)

keras_core/backend/common/variables.py
As discussed in #719 
`torch.Size` is a subclass of tuple, so it might break the logic in `standardize_shape` that `isinstance(e, int)` is invalid for `torch.Tensor`.
cc @haifeng-jin
=> Fix `standardize_shape`

keras_core/applications/densenet.py, keras_core/applications/mobilenet_v3.py, keras_core/ops/operation.py, keras_core/ops/operation_test.py
This PR fixes the naming error in MobileNetV3 and DenseNet caused by the introduction of `name_scope`.
A new assertion in `keras_core/ops/operation.py` and corresponding tests have been added.
=> Fix naming in `mobilenet_v3` and `densenet`

keras_core/ops/nn.py
As promised, I have begun enhancing the docstrings and adding easy-to-understand examples. 
The goal is to make the Keras core documentation a pleasant resource for learning deep learning. 
The objective of these straightforward examples is to facilitate understanding without delving into complex mathematics.
=> Enhance docstrings + easy to understand examples (nn.py)

keras_core/layers/preprocessing/hashed_crossing.py, keras_core/trainers/epoch_iterator.py, keras_core/utils/tf_utils.py
In all cases, `arg_description` already contains the article "the". The error message would then contain "the" twice, for instance "Intead, the the targets should...".
Also fixed some formatting issues caught by lint.
=> Fix error message which would print the article "the" twice.

keras_core/layers/convolutional/conv_transpose_test.py
Removes `tf.keras` dependency from transposed conv test and replaces it with numpy expected results implementation.
=> Removes `tf.keras` from transposed conv test

keras_core/layers/preprocessing/rescaling.py, keras_core/layers/preprocessing/rescaling_test.py
The `EfficientNet` in Keras applications uses the Rescaling layer with a vector (`shape=(channels,)`) as the scale.
See https://github.com/keras-team/keras-core/blob/v0.1.5/keras_core/applications/efficientnet.py#L333-L335
=> Fix channels_first format bug for rescaling layer

keras_core/ops/math.py
(Sorry for the typo in previous PR)
The argument order in the stft and istft functions was incorrect.
`(sequence_length, sequence_stride, fft_length, center, window)` should be `(sequence_length, sequence_stride, fft_length, window, center)`
This PR addresses it by using kwargs to validate the provided args.
=> Fix argument order in stft and istft

keras_core/ops/numpy.py
The `Squeeze` op is confused as to whether it should accept `axis` in the constructor or as an argument in `call` / `compute_output_spec`. This makes it self-consistent, and what I think is consistent with the other ops.
=> fixed squeeze axis inconsistency

keras_core/distribution/distribution_lib.py, keras_core/layers/preprocessing/category_encoding_test.py, keras_core/layers/preprocessing/discretization_test.py, keras_core/layers/preprocessing/index_lookup_test.py, keras_core/layers/preprocessing/integer_lookup_test.py, keras_core/layers/preprocessing/normalization_test.py, keras_core/layers/preprocessing/random_brightness_test.py, keras_core/layers/preprocessing/random_contrast_test.py, keras_core/layers/preprocessing/random_crop_test.py, keras_core/layers/preprocessing/random_flip_test.py, keras_core/layers/preprocessing/random_rotation_test.py, keras_core/layers/preprocessing/random_translation_test.py, keras_core/layers/preprocessing/random_zoom_test.py, keras_core/layers/preprocessing/rescaling_test.py, keras_core/layers/preprocessing/string_lookup_test.py, keras_core/layers/preprocessing/text_vectorization_test.py
Replaces `tf.data` usages with `from tensorflow import data as tf_data` in preprocessing tests.
=> Replace `tf.data` with `tf_data` in preprocessing tests

keras_core/activations/activations_test.py, keras_core/ops/nn.py
Fixing the softmax function in keras_core.ops to handle tuple axes.
**Why :**
[One ](https://github.com/keras-team/keras-core/blob/38c9f7d1691d5d7af79811afd3f5df4e53352094/keras_core/activations/activations_test.py#L34C7-L34C32)of the TODOs 
**Changes**:
1. Updated softmax function in keras_core.ops.
2. Added back test test_softmax_3d_axis_tuple to validate changes.
3. Added comprehensive test cases for the softmax activation function to ensure its correctness and robustness across various scenarios: 
-               Handle 1D inputs, 
-               Support higher-dimensional tensors.
-               Process negative axis values.
-               Higher dimensions with even higher axes.
=> Fix bug: Softmax function to support tuple axes + Add more tests

keras_core/activations/activations_test.py, keras_core/ops/nn.py
The PR aims to fix a bug associated with the `log_softmax` function when provided with tuple `axes`. In addition, several tests have been added to ensure the correctness of the function across various scenarios.
**Key Updates**:
1. **File**: `keras_core/ops/nn.py`
- Modified the `log_softmax` function to handle tuple `axes`.
2. **File**: `keras_core/activations/activations_test.py`
- Added a reference function `_ref_log_softmax` that implements the log-softmax operation for testing.
- Introduced various tests for the `log_softmax` function, including:
- `test_log_softmax_2d_axis_0`
- `test_log_softmax_3d_axis_tuple`
- `test_log_softmax_1d`
- `test_log_softmax_higher_dim`
- `test_log_softmax_higher_dim_multiple_axes`
- `test_log_softmax_negative_axis`
- `test_temporal_log_softmax`
=> Fix bug: Log_Softmax with tuple axes + Add tests

examples/keras_io/structured_data/tabtransformer.py, examples/keras_io/tensorflow/structured_data/tabtransformer.py
Port tab transformer example to keras core. Tried testing on all backends and the StringLookup layer doesn't work with torch and jax backends. [COLAB to reproduce](https://colab.research.google.com/drive/1XV_XtJrEyp2hzsJUGaVawVz9Y5NnfDuR?usp=sharing)
=> Port tab transformer example to keras core

keras_core/metrics/accuracy_metrics.py
It is better to demonstrate those metrics using suitable loss functions rather than `mse`
=> Update example losses on docstrings

keras_core/losses/loss.py, keras_core/losses/loss_test.py
This fix ensures that losses evaluated with a `sample_weights == ops.cast(mask, "float32")` are the same as those evaluated with either argument but not both `None`. Note this `total` is consistent with the `batch_size` used in `reduce_values`, corresponding to the total size of all elements as opposed to the leading dimension. Another fix might be to leave `apply_mask` alone and change `reduce_values` to divide by the leading dimension only rather than the total size.
I'm unsure of a concise way to unit test this because AFAIK there's no way to pass a mask in using only the public API...
=> fixed apply_mask bug in losses

keras_core/layers/preprocessing/center_crop_test.py, keras_core/layers/preprocessing/resizing_test.py
Replaces `tf.keras` in Center Crop and Resizing pre-processing layers.
This completes the task of removing `tf.keras` in all test reference outputs.  Its only used in `legacy/saving/legacy_h5_format.test`
=> Replace `tf.keras` in center-crop and resize tests

keras_core/metrics/confusion_metrics_test.py, keras_core/metrics/metrics_utils.py
Consider the case:
```python
import keras_core
import numpy as np
label = np.random.randint(0, high = 2, size = 100)
keras_core.metrics.Precision(class_id = 20)(label, label)
```
If one of the inputs are 1D and `class_id` is provided, the code will still execute without any errors, but it seems like the results may not be what we expect. It effectively reduces the inputs to a single value right now.
So I added a check before using `class_id` 🤔 or is this something intended? If not, the tests need to be updated aswell.
=> Add a check for class_id argument

keras_core/models/model_test.py, keras_core/trainers/compile_utils.py, keras_core/trainers/compile_utils_test.py, keras_core/trainers/trainer_test.py
The name `"mse"` was not kept as the name as the metric, but used `"mean_square_error"` instead, when `model.compile(..., metrics=["mse"])`.
The cause of the bug is custom names were only assigned when creating `MeanMetricWrapper` from `Metric`, but some metrics were created directly by deserialization as a `MeanMetricWrapper`.
The solution is to do the name assignment for all metrics before returning.
=> Keep "mse" as the metric name in the log

keras_core/activations/activations.py, keras_core/backend/common/variables.py, keras_core/backend/numpy/image.py, keras_core/backend/tensorflow/image.py, keras_core/layers/attention/multi_head_attention.py, keras_core/layers/core/wrapper_test.py, keras_core/layers/layer.py, keras_core/layers/normalization/batch_normalization.py, keras_core/layers/normalization/spectral_normalization.py, keras_core/layers/normalization/spectral_normalization_test.py, keras_core/layers/pooling/average_pooling_test.py, keras_core/layers/pooling/max_pooling_test.py, keras_core/layers/preprocessing/hashed_crossing_test.py, keras_core/layers/preprocessing/normalization.py, keras_core/layers/preprocessing/random_contrast.py, keras_core/layers/rnn/bidirectional.py, keras_core/layers/rnn/rnn.py, keras_core/testing/test_case.py
The main goal of this is to add dtype support for the MHA layer. E.g. get `MultHeadAttention(dtype="mixed_float16")` to work correctly (it does not today).
But tried out adding a mixed precision test for all layers, which caught some other bugs.
=> Fixed misc mixed precision issues

keras_core/layers/normalization/layer_normalization.py
Previously, under mixed precision, we would autocast full precision variables to half precision, then manually cast back to full precision.
Possibly this would compile away (no idea), but is certainly very slow in eagerly. We should set `autocast=False` to avoid the needless type conversion loop.
=> Don't double cast layer norm weights in mixed precision

keras_core/trainers/trainer.py
The old implementation is here: https://github.com/keras-team/keras/blob/v2.14.0-rc0/keras/engine/training.py#L823
=> Add `loss` attribute for backward compatibility

integration_tests/distribute_training_test.py, integration_tests/model_visualization_test.py, keras_core/metrics/confusion_metrics_test.py, pyproject.toml, setup.cfg, shell/format.sh, shell/lint.sh
This PR fixes a couple of issues:
1. **Bad lint was not causing the CI to fail**: Happens becuase the `-e` flag was set on the shebang line and the CI action was being run as `bash shell/lint.sh`, therefore the `-e` flag was being ignored. Fixed by using `set -e` versus `#!/bin/bash -e`.
For instance in [this build](https://github.com/keras-team/keras-core/actions/runs/6016918719/job/16321975971), lint clearly fails (see screenshot below) but the "Check the code format" action succeeds.
2. **Moved exclude/include for isort, black and flake8 to the config files (`pyproject.toml` and `setup.cfg`)**: This puts all the configs in one place and makes it easy to invoke each tool separately during development. **Note:** I kept the `examples/` and `guides/` directories excluded since it seemed …
=> Make sure the Test CI action fails on bad lint

keras_core/backend/jax/core.py, keras_core/backend/jax/distribution_lib.py, keras_core/distribution/distribution_lib_test.py
The jax varaible will preserve the layout information at the init time, and will reuse it for any future assigned the value.
This will fix the issue for keras nlp/cv model that does the weight loading after the model creation, which unshard the variable back to the device:0
=> Fix the Jax distributed variable load issue.

keras_core/backend/jax/layer.py, keras_core/backend/numpy/layer.py, keras_core/backend/tensorflow/layer.py, keras_core/layers/layer.py, keras_core/models/functional.py, keras_core/models/sequential.py
This is trying to put us in a more consistent place with respect to implicitly vs explicitly built layers. Explicitly calling `build()` will now...
- Record the build config passed to the layer.
- Lock the layer so state cannot be mutated.
The last remaining difference is that implicitly we will attempt the build the layer by calling it symbolically, explicitly we do not. We could revisit that if we wanted, but I think that would be a slightly more complex change.
=> Always save the build config when building a layer

keras_core/layers/preprocessing/random_brightness.py, keras_core/layers/preprocessing/random_flip.py, keras_core/layers/preprocessing/random_rotation.py, keras_core/layers/preprocessing/random_translation.py, keras_core/layers/preprocessing/random_zoom.py
* Replace `inputs.shape` with `backend.shape`
* Convert values to float before doing floating point arithmetic.
This fixes #814 for other random augmentations.
Errors it fixes:
```
Arguments received by RandomZoom.call():
• inputs=tf.Tensor(shape=(None, None, None, 3), dtype=float32)
• training=True
height_translate = ag__.ld(height_translate) * ag__.ld(height)
ValueError: Exception encountered when calling RandomTranslation.call().
Tried to convert 'y' to a tensor and failed. Error: None values not supported.
Arguments received by RandomTranslation.call():
• inputs=tf.Tensor(shape=(None, None, None, 3), dtype=float32)
• training=True
x_offset = (ag__.ld(image_width) - 1 - (ag__.ld(cos_theta) * (ag__.ld(image_width) - 1) - ag__.ld(sin_theta) * (ag__.ld(image_height) - 1))) / 2.0 …
```
=> Uses `backend.shape`  in random preprocessing

keras_core/backend/common/backend_utils.py, keras_core/backend/jax/nn.py, keras_core/backend/numpy/nn.py, keras_core/backend/torch/nn.py, keras_core/layers/convolutional/conv_transpose_test.py
This PR refactors the way padding arguments are handled by Conv Transpose functions, to fix the misalignment between backends (see https://github.com/keras-team/keras-core/issues/774).
The main change is to create two functions to convert the padding arguments from the Keras convention to the JAX / Torch conventions. As raised in the issue, it seems to me that some padding configurations are not possible to be translated in Torch; in which case, a warning is raised when using those configurations on a Torch backend.
Some caveat / interrogations:
* The padding conventions of conv transpose are not always very well documented by the original backends, so I had to infer their implementation. This PR implements the best of my understanding, but could be missing some edge case.
* I added some …
=> Refactor conv_transpose padding

keras_core/ops/operation_utils.py, keras_core/ops/operation_utils_test.py
1. Adding  several test functions covering various scenarios for functions such as `compute_pooling_output_shape`, `compute_conv_output_shape`, `compute_reshape_output_shape`, and `reduce_shape`. Tests include different padding types, strides, and input shapes to ensure comprehensive coverage.
2. Fixing the `reduce_shape` function to work correctly with different `axis` and `keepdims` parameters.
=> Fix `reduce_shape` + Add tests to operation_utils_test.py

examples/keras_io/nlp/neural_machine_translation_with_keras_nlp.py
1. colab [notebook](https://colab.research.google.com/drive/1VOr8wDFMQQbPoy6tFfAWguZ6GLDtJam1?usp=sharing)
2. diff b8f73d5
- keras -> keras_croe
- some tf ops -> keras_core.ops
- tf.data -> tf_data
- remove `mask_zero = True` because it causes an error and is not necessary for this example
=> Convert "English-to-Spanish translation with KerasNLP" to keras-core

keras_core/backend/common/variables.py, keras_core/backend/common/variables_test.py, keras_core/backend/numpy/numpy.py, keras_core/backend/torch/numpy.py, keras_core/ops/numpy_test.py
One of the advantages of Keras Core is that we can integrate the workflow with different backends.
For example, we can train a tensorflow model using a torch dataloader.
However, operations containing `standardize_dtype` might fail when the dtype is `torch.Tensor.dtype` and the backend is NOT torch.
```python
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import torch
from keras_core import ops
x = torch.randn(4, 16, 16, 3)
y = ops.convert_to_tensor(x, dtype=x.dtype)  # failed w/o this PR
print(y.dtype)
```
This PR has addressed the issue by implementing a better check for `torch.Tensor.dtype`.
A unit test for this behavior has been included.
=> Improve the flexibility of `standardize_dtype` and fix `pad` in torch backend

keras_core/backend/jax/trainer.py, keras_core/trainers/trainer.py
1. The key fix here is too unwrap the jax.array from the trainable_variable/optimizer_variable before feed them to jax.jit train/eval function. Somehow JAX wasn't able to infer the sharding spec from the kerasVariable, which cause it to run with fully replicated weights.
2. Lift the data distribution logic out and put it outside of the jitted function. I noticed this issue when I debug the sharding setting.
3. Enforce the sharding constrain for the training state before the end of the jitted function. This will make sure the training state output have the same sharding step as the input. Otherwise it will cause jax to recompile the training function due to the sharding change.
4.  I don't have a way to unit test this, since we can't easily step into a jitted function. The early test …
=> Fix the distribution logic for the JAX trainer.

keras_core/trainers/trainer.py
Just noticed we are missing a compile docstring. Probably good to add.
Adapter from `tf.keras` with a few changes.
=> Add a docstring for compile

.github/workflows/actions.yml, setup.py
Currently the tests are running with `JAX==0.4.13` which was the last version that supported Python 3.8.  The latest `jax` version is `0.4.14`.  TensorFlow also has dropped python 3.8 in the upcoming `2.14` release.  Numpy has already dropped it.  So updating `keras-core` to use Python 3.9 as the minimum version.
=> Update minimum python version to 3.9 to align with TF/JAX

keras_core/backend/jax/trainer.py
The current eager_build will use eager tensor to run the forward path of the model to trigger variable creation, but this will bring non-trivial memory consumption from the forward path, and will cause OOM when the model are large, and designed for distribution computation.
This PR will use the kerasTensor instead, which doesn't consume any memory.
Verified with local colab for memory consumption.
=> Update the eager_build logic for jax trainer.

keras_core/optimizers/base_optimizer.py
Style nit, remove return type from `optimizer.apply`, so it is 1-1 with the signature for `optimizer.stateless_apply`. We can leave the iterations return type on `apply_gradients` for compat with tf.keras. It seems mostly for compat, and has no stateless version.
=> Update return type for optimizer.apply

keras_core/layers/layer.py, keras_core/layers/layer_test.py
Sometimes in preprocessing layers our dtype is not a floating point dtype. In these cases we should never autocast, it would error immediately.
=> Fix autocast scope again

keras_core/backend/jax/numpy.py, keras_core/backend/jax/trainer.py, keras_core/backend/tensorflow/optimizer.py, keras_core/backend/tensorflow/trainer.py, keras_core/backend/torch/trainer.py, keras_core/callbacks/tensorboard.py, keras_core/callbacks/tensorboard_test.py, keras_core/ops/core.py, keras_core/ops/core_test.py, keras_core/optimizers/__init__.py, keras_core/optimizers/base_optimizer.py, keras_core/optimizers/loss_scale_optimizer.py, keras_core/optimizers/loss_scale_optimizer_test.py, keras_core/optimizers/optimizer_test.py, keras_core/trainers/trainer.py, keras_core/trainers/trainer_test.py
This is the big missing piece we need for feature parity when running mixed precision training compared to tf.keras.
Fixes #571
=> Add a loss scale optimizer

keras_core/utils/python_utils.py, keras_core/utils/python_utils_test.py
Increase test coverage in Increase test coverage in `keras_core/utils`
=> Increase test coverage in  `keras_core/utils`

README.md
With `keras_core` users has to import the **backend** first before importing `keras_core`. It has to be documented in **README.md** for better visibility and reach to the community.
Fixes #833
=> Add a note in README.md regarding pre-import of backend

keras_core/utils/summary_utils.py, keras_core/utils/summary_utils_test.py
The sample output with optimizer weights is like below:
```
Model: "language_model"
┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃ Param # ┃ Connected to         ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩
│ padding_mask        │ (None, None)      │       0 │ -                    │
│ (InputLayer)        │                   │         │                      │
├─────────────────────┼───────────────────┼─────────┼──────────────────────┤
│ token_ids           │ (None, None)      │       0 │ -                    │
│ (InputLayer)        │                   │         │                      │
├─────────────────────┼───────────────────┼─────────┼──────────────────────┤
│ opt_backbone …
```
=> Add optimizer weights to the model summary.

keras_core/backend/tensorflow/numpy.py, keras_core/layers/core/dense_test.py, keras_core/layers/core/embedding_test.py, keras_core/layers/core/identity.py, keras_core/layers/core/identity_test.py, keras_core/ops/numpy_test.py, keras_core/testing/test_case.py
Added `tf.SparseTensor` support for ops:
- matmul
- take
Added `tf.SparseTensor` support for core layers:
- Dense
- Embedding
- Identity
=> Add support for Tensorflow SparseTensors: core layers.

keras_core/backend/common/keras_tensor_test.py, keras_core/backend/common/stateless_scope_test.py, keras_core/backend/common/variables_test.py
This PR aaims to enhance the test coverage in the `keras_core/backend` module.
**Highlights:**
1- Introduced comprehensive unit tests in `keras_core/backend/common/keras_tensor_test.py` to ensure the proper functioning and error handling of various tensor-related operations, such as:
- Boolean conversion of tensors.
- Iterating over tensors.
- Various symbolic tensor operations including addition, multiplication, subtraction, and more.
2- Augmented tests in `keras_core/backend/common/stateless_scope_test.py` to validate:
- Error handling for invalid keys and values in state mapping.
3- Expanded tests in `keras_core/backend/common/variables_test.py`:
- Introduced tests for variable name validation, ensuring names are strings and don't contain certain characters.
- Ensured proper error …
=> Increase test coverage in `keras_core/backend`

keras_core/backend/tensorflow/numpy.py, keras_core/layers/reshaping/flatten.py, keras_core/layers/reshaping/flatten_test.py, keras_core/layers/reshaping/permute.py, keras_core/layers/reshaping/permute_test.py, keras_core/layers/reshaping/reshape.py, keras_core/layers/reshaping/reshape_test.py, keras_core/ops/numpy.py, keras_core/ops/numpy_test.py, keras_core/testing/test_case.py
Added `tf.SparseTensor` support for ops:
- reshape
- transpose
Added `tf.SparseTensor` support for reshaping layers:
- Flatten
- Permute
- Reshape
=> Add support for Tensorflow SparseTensors: reshaping layers.

keras_core/trainers/data_adapters/array_data_adapter.py, keras_core/trainers/data_adapters/array_data_adapter_test.py, keras_core/trainers/data_adapters/data_adapter_utils.py
In tf.keras, int array input is not converted to floatx. In keras-core, all array input is converted to flaotx.
This feels both like a regression compatibility wise, and quite surprising generally for subclass models. There are plenty of valid reasons to pass some int input to a model.
https://colab.research.google.com/gist/mattdangerw/2a030f1b14ec4fa3347711e84541e6d7/array-conversion-discrepency.ipynb
=> Don't convert int array input to floatx

keras_core/layers/normalization/spectral_normalization_test.py, keras_core/layers/preprocessing/hashed_crossing.py, keras_core/layers/preprocessing/hashed_crossing_test.py, keras_core/testing/test_case.py
This uncovered an issue in one layer and an issue in a test.
=> `run_layer_test` also runs symbolic calls when `input_data` is provided.

keras_core/utils/dtype_utils.py, keras_core/utils/dtype_utils_test.py
Bug Fixe:
Corrected the `dtype_size` function by fixing the comparison logic. Previously, if the `dtype size` of the current tensor was greater than the `highest_float`, the `highest_float` value was not being updated correctly. This has been addressed by explicitly comparing the dtype sizes.
Test Coverage:
A new file `dtype_utils_test.py` has been added, ensuring rigorous testing of the utility functions. 
The tests cover:
- Checking size of multiple data types including float and int variants.
- Verifying the `is_float` function's accuracy in recognizing float dtypes.
- Extensively testing the `cast_to_common_dtype` function, ensuring tensors are casted to the most precise common `dtype`, especially covering edge cases involving `float16`, `bfloat16`, and other mixed dtypes.
=> Increase test coverage in utils + Fix Bug in `cast_to_common_dtype` 

keras_core/backend/numpy/core.py, keras_core/ops/core_test.py
We should return `x` instead of `None` in numpy's `stop_gradient`.
A unit test has been added to verify the return value.
=> Fix `stop_gradient` in np

keras_core/utils/summary_utils.py, keras_core/utils/summary_utils_test.py
Optimizer can be `None` (e.g. for just running inference). We should be careful not to assume it is always set when printing out model summary.
=> Fix summary when optimizer is None

keras_core/backend/jax/nn.py, keras_core/backend/numpy/nn.py, keras_core/backend/tensorflow/nn.py, keras_core/backend/torch/nn.py, keras_core/layers/normalization/batch_normalization.py, keras_core/layers/normalization/group_normalization.py, keras_core/layers/normalization/layer_normalization.py, keras_core/ops/nn.py, keras_core/ops/nn_test.py
EDITED:
This PR adds `ops.nn.moments` and improves some normalization layers by fast mean and variance computation.
This PR also addresses the overflow & underflow issue when the input tensor is float16.
There are two approaches to compute variance:
- $Var = E[|x - E[x]|^2])$ (stable but slower)
- $Var = E[|x|^2] - |E[x]|^2$ (fast but unstable)
|backend|layer|manual implementation (before this PR)|`ops.nn.moments` (fast but unstable, this PR)|`ops.nn.moments` (stable but slower)|
|-|-|-|-|-|
|tensorflow|BatchNormalization|58ms|58ms|69ms|
|jax|BatchNormalization|63ms|63ms|75ms|
|torch|BatchNormalization|73ms|72ms|74ms|
|tensorflow|GroupNormalization|89ms|61ms|73ms|
|jax|GroupNormalization|96ms|72ms|83ms|
|torch|GroupNormalization|72ms|74ms|76ms| …
=> Add `ops.nn.moments` and speed-up normalization layers

keras_core/utils/summary_utils.py, keras_core/utils/summary_utils_test.py
Most people will call `summary()` before `fit()`. Doing so will usually mean the optimizer would show up as 0 parameters, which is misleading.
=> Don't show optimizer params if not optimizer or not built

keras_core/backend/common/variables.py
Making multi backend dtype comparisons for code based on keras-core is tricky. Torch has dtype classes such that
`torch_tensor.dtype is string_dtype` will always be false.
We use `standardize_dtype` extensively in our own code and should expose it to clients. `is_float_dtype` and `is_int_dtype` we can include as useful helpers.
=> Export dtype utils in `keras_core.backend`

.github/workflows/actions.yml
Fixes https://github.com/keras-team/keras-core/issues/881.
This PR ensures all the jobs in the `actions.yml` workflow run with read-only permissions instead of the default `write-all`.
=> Set actions.yml to run with read-only permissions

keras_core/utils/dtype_utils.py
My model contains some `uint` non trainable variables that triggered an exception when calling the `model.summary()` method.
I added the missing dtypes.
=> Add missing dtypes.

keras_core/trainers/data_adapters/torch_data_adapter.py
As mentioned in #550, one remaining change from #750 is to first move the torch tensor to the CPU before passing it to a numpy array. 
This is relevant for the Metal GPU case. While calling `.cpu()` is harmless on a torch tensor already in the CPU, in my observation directly moving the tensor from Metal to numpy returns an error, hence the need to move it first.
=> fixes #550: move torch tensors to cpu before to numpy array

keras_core/export/export_lib.py
@mattdangerw @fchollet 
This prevents a hard dependency on JAX by moving the import for JAX2TF into the function where it is used.
Thanks!
=> Make jax2tf import conditional

keras_core/layers/layer.py, keras_core/layers/layer_test.py, keras_core/trainers/trainer_test.py
As discussed in https://github.com/keras-team/keras-core/pull/897, we separate the metrics related variables from non-trainable variables, so that we can properly leverage the jax memory donation.
This will also allow us to skip the saving for metrics variables during checkpoint/savemodel
=> Separate the metrics variables from non-trainable variables.

.github/workflows/actions.yml, pyproject.toml, setup.cfg
This PR does a few things:
1. Excludes `keras_core/legacy` from coverage metrics since this module there for BC reasons
2. Adds the test backend (jax, tensorflow, torch, numpy) to flags to allow tracking coverage metrics per backend. Note that each backend's coverage will be lower than the aggregate (e.g. `keras_core` will have higher coverage than `keras_core-jax`), so this flag should be used to track trends rather than impose thresholds.
3. Moves `coverage` and `pytest` configuration from `setup.cfg` to `pyproject.toml` to keep all project configs in toml vs cfg (unfortuantely `flake8` configs need to stay in `setup.cfg` since flake8 doesn't support `pyproject.toml` yet: https://github.com/PyCQA/flake8/issues/234)
4. Adds `fail_ci_if_error: true` to codecov upload steps to fail the CI …
=> [GHA] fix several codecov issues 

examples/keras_io/pytorch/torchvision_keras.py
This PR adds an example to fine-tune pre-trained models from [TorchVision](https://pytorch.org/vision/stable/index.html) using KerasCore.
Notebook: https://colab.research.google.com/drive/14CkRocZrvGxFCn6-zOaFC_gji35nF-Fc?usp=sharing
Linked Issue: https://github.com/keras-team/keras-core/issues/883
=> Add example to fine-tune TorchVision models using Keras

keras_core/layers/merging/merging_test.py
They are almost identical for every merging layer.
This simplifies adding tests that apply to every layer. This is in preparation for adding sparse tensors support.
=> Refactor merging layers tests as parametrized tests.

keras_core/backend/torch/numpy.py, keras_core/ops/numpy_test.py
Fixes #544 
Unit test has been updated to verify the behavior consistency across backends.
```python
...
x = np.ones(shape=(0,))
self.assertEqual(len(knp.split(x, 2)), 2)
self.assertEqual(len(knp.Split(2)(x)), 2)
...
```
=> Makes `ops.split` in torch consistent with other backends

examples/keras_io/nlp/multiple_choice_task_with_transfer_learning.py
This PR will add the MultipleChoice example with Transfer Learning using KerasNLP and KerasCore as mentioned in #791 .
Here is the colab demo: [Colab](https://colab.research.google.com/drive/18EhnA-912bBD-4mK81DFcUYh592ikCdm?usp=sharing)
I'm open to open to feedback to make this example more suitable for Keras users.
> I didn't run the `python autogen.py add_example vision/script_name` script as in the examples in this repo, I couldn't see any `/ipynb`, `/md`, or `/img` directories.
=> Add: `MultipleChoice with Transfer Learning` example

keras_core/backend/jax/rnn.py, keras_core/layers/__init__.py, keras_core/layers/rnn/rnn.py, keras_core/layers/rnn/stacked_rnn_cells.py, keras_core/layers/rnn/stacked_rnn_cells_test.py
This PR address several issues:
1. The existing RNN layer is not training properly due the usage of a fresh StatelessScope in the jax.lax.scan loop. This is causing all the trainable variables to miss the mapping to the actual value in the training loop. Update them to use the parent Stateless scope if it is there. This will address the training issue https://github.com/keras-team/keras-core/issues/322
2. The RNN layers with dropout will have a RNG seed update in the step function, which is not allowed by the jax.lax.scan. We noticed this issue since the updated seed is traced for non-trainable variable, and raise error when we try to put sharding constraint for distribution. Added a new method to pre-populate the dropout mask on the layer and make the inner_loop to be stateless.
3. …
=> Fix JAX RNN backend issue.

keras_core/export/export_lib.py, keras_core/export/export_lib_test.py
This PR is a temporary fix in response to the incompatibility between the latest JAX release and latest stable TF release, affecting the export API and its use of JAX2TF.
=> Adds JAX version checking for Export

keras_core/backend/jax/image.py, keras_core/backend/numpy/image.py, keras_core/ops/image_test.py, keras_core/ops/nn_test.py
This PR resolves the inconsistency in `affine_transform` between numpy and jax due to the unfixed `scipy.ndimage.map_coordinates`.
Previous:
- jax: fixed version of `map_coordinates` in `ops.image.affine_transform`
- numpy: unfixed version of `map_coordinates` in `ops.image.affine_transform`
References:
- https://github.com/google/jax/issues/5687
Let's check if the CI is functioning as expected.
EDITED:
I have found that using `interpolation="nearest"` leads to test failures in torch and jax. The root cause might be differences in the output indices, resulting in significant error in image values.
Currently, I have no idea how to fix it, so `self.skipTest` has been added.
EDITED2:
After the change, I encountered a failure in `nn.moments` in jax. `atol` and `rtol` have been increased to …
=> Fix the inconsistency in `affine_transform` between numpy and jax

keras_core/backend/tensorflow/numpy.py, keras_core/layers/merging/add.py, keras_core/layers/merging/average.py, keras_core/layers/merging/base_merge.py, keras_core/layers/merging/merging_test.py, keras_core/layers/merging/multiply.py, keras_core/layers/merging/subtract.py, keras_core/ops/numpy.py, keras_core/ops/numpy_test.py
Added `tf.SparseTensor` support for ops:
- add
- concatenate
- maximum
- minimum
- multiply
- subtract
Added `tf.SparseTensor` support for merging layers:
- Add
- Average
- Concatenate
- Maximum
- Minimum
- Multiply
- Subtract
Note that the `Dot` merging layer will be addressed in a separate PR.
=> Add support for Tensorflow SparseTensors: merging layers.

keras_core/backend/torch/image.py, keras_core/layers/preprocessing/random_translation_test.py, keras_core/ops/image.py, keras_core/ops/image_test.py
Since `map_coordinates` has been implemented in torch, we can now use it to perform `affine_transform`.
Several performance issues have been resolved to align with the original implementation using `tnn.grid_sample`.
|`tnn.grid_sample`|`ops.image.map_coordinates`|
|-|-|
|1.702s|0.255s|
- `tnn.grid_sample` (original): [colab](https://colab.research.google.com/drive/1MIIEbsG9LoNgXAuLX1odp5Qkyuu83Ahz?usp=sharing)
- `ops.image.map_coordinates` (this PR): [colab](https://colab.research.google.com/drive/1YW7qEMjksKq6iC3YRbAv9Ss1Iow5VKQ3?usp=sharing)
The codebase will be cleaner and more consistent with other backends after the changes.
=> Refactor torch's `affine_transform`

keras_core/ops/numpy.py, keras_core/saving/serialization_lib.py, keras_core/saving/serialization_lib_test.py
Models that contain slicing cannot be serialized because of the missing handling of slices in the `(de)serialize_keras_object` functions.
Thus a simple functional as this one.
```python
x = inp = Input(...)
...
x = x[:, 1:-1, 1:-1]
...
fn = Functional(inp, x)
```
could not be serialized.
Now it's possible with this fix.
=> Slice serialization

keras_core/ops/function.py
See https://github.com/keras-team/keras-core/issues/931 for more info. And other workaround we could consider.
=> Hacky fix for dictionary output with tf 2.14

keras_core/backend/tensorflow/numpy.py, keras_core/layers/merging/merging_test.py, keras_core/ops/numpy.py, keras_core/ops/numpy_test.py
Added `tf.SparseTensor` support for ops:
- matmul (sparse support was very partial before this PR)
- squeeze
- expand_dims
Added `tf.SparseTensor` support for merging layer:
- Dot
=> Add support for Tensorflow SparseTensors: Dot merging layer.

keras_core/callbacks/__init__.py, keras_core/callbacks/backup_and_restore_callback.py, keras_core/callbacks/backup_and_restore_callback_test.py
Based on the [callback issue](https://github.com/keras-team/keras-core/issues/23)
=> Backup and restore callback

keras_core/backend/common/backend_utils_test.py
Increase-test-coverage in `backend_utils`
=> Increase-test-coverage in `backend_utils`
