keras_core/trainers/trainer.py
keras_core/trainers/trainer_test.py

Weighted metrics without metrics

---

keras_core/initializers/constant_initalizers_test.py
keras_core/initializers/constant_initializers.py
keras_core/initializers/random_initializers_test.py

Added following features:-
- standard dtypes edit in **constant_initializers.py**
- Added tests for the constant initializers

Constant Initializer Error fixed

---

keras_core/backend/torch/nn.py
keras_core/layers/convolutional/conv_transpose_test.py
keras_core/ops/numpy.py

The padding computation was wrong.

Fix Torch conv transpose

---

examples/keras_io/tensorflow/vision/cct.py

Attached git diff to original repo: 
Update Imports
Remove TensorFlow Addons Dependency
Move Sequence Pooling code and description to separate layer
Change file name in checkpoint callback
[Colab Notebook](https://colab.research.google.com/drive/11e7Eg8blqhuTz2gc9g4qFjbL62q7Um-g?usp=sharing)
[cct_diff.txt](https://github.com/keras-team/keras-core/files/12075550/cct_diff.txt)

Convert to Keras_Core: Compact Convolutional Transformer

---

keras_core/layers/core/input_layer_test.py
keras_core/ops/numpy.py

Hey @fchollet,
do let me know:-
- Any test/edge cases I have missed

Input layer test

---

keras_core/backend/torch/optimizers/torch_adamw.py
keras_core/backend/torch/optimizers/torch_optimizer.py
keras_core/optimizers/adamw.py
keras_core/optimizers/adamw_test.py

Also changed the original AdamW to extend Adam to remove code duplication.

Add AdamW implementation with torch parallel ops

---

keras_core/backend/torch/optimizers/torch_optimizer.py
keras_core/backend/torch/optimizers/torch_rmsprop.py
keras_core/optimizers/rmsprop_test.py

Add RMSprop for Torch

---

keras_core/backend/torch/optimizers/torch_adadelta.py
keras_core/backend/torch/optimizers/torch_optimizer.py
keras_core/backend/torch/optimizers/torch_rmsprop.py
keras_core/backend/torch/optimizers/torch_sgd.py
keras_core/optimizers/adadelta_test.py

The PR also contains minor bug fixes for SGD and RMSprop when using momentum.

Add Adadelta for torch

---

keras_core/backend/torch/optimizers/torch_adamax.py
keras_core/backend/torch/optimizers/torch_optimizer.py
keras_core/optimizers/adamax_test.py

Add adamax for torch

---

examples/keras_io/tensorflow/audio/speaker_recognition_using_cnn.py
examples/keras_io/tensorflow/audio/uk_ireland_accent_recognition.py

git diff with the original example gave the following
@@ -1,8 +1,9 @@
"""
Title: English speaker accent recognition using Transfer Learning
Author: [Fadi Badine](https://twitter.com/fadibadine)
+Converted to Keras Core by: [Fadi Badine](https://twitter.com/fadibadine)
Date created: 2022/04/16
-Last modified: 2022/04/16
+Last modified: 2023/07/19
Description: Training a model to classify UK & Ireland accents using feature extraction from Yamnet.
Accelerator: GPU
"""
@@ -40,7 +41,7 @@ pip install -U -q tensorflow_io
"""
SEED = 1337
-EPOCHS = 100
+EPOCHS = 1
BATCH_SIZE = 64
VALIDATION_RATIO = 0.1
MODEL_NAME = "uk_irish_accent_recognition"
@@ -104,7 +105,7 @@ import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_io as tfio
-from tensorflow import keras …

Converted UK Ireland accent recognition to work with Keras Core

---

examples/keras_io/tensorflow/rl/actor_critic_cartpole.py

Port Actor Critic Example to Keras Core.
Update imports
Update deprecated parts from gym
[actor_critic_keras_core.diff.txt](https://github.com/keras-team/keras-core/files/12096421/actor_critic_keras_core.diff.txt)
[Colab Notebook](https://colab.research.google.com/drive/1iRnq6Y00K24IY_IojYMEx_iRpfgnvZbN?usp=sharing)

port actor_critic_cartpole to keras core

---

keras_core/ops/operation_utils.py

Hi @fchollet @chenmoneygithub ,
I have Added docstrings to the required functions. Kindly review and let me know if there are any modifications to be made.

Update operation_utils.py - Added docstrings

---

examples/keras_io/tensorflow/vision/deeplabv3_plus.py
examples/keras_io/vision/deeplabv3_plus.py

Update imports
change tf.keras to keras
repace tensorflow operations with keras ops
[Colab Notebook](https://colab.research.google.com/drive/1uk-k_AE1WDzxoiZOQARVzUv0IHIDnfVA?usp=sharing)
[deeplabv3_plus_keras_core.diff.txt](https://github.com/keras-team/keras-core/files/12098216/deeplabv3_plus_keras_core.diff.txt)

Converted to Keras Core: DeepLabV3Plus

---

examples/keras_io/tensorflow/vision/reptile.py

Port few shot learning with reptile

---

keras_core/backend/common/keras_tensor.py
keras_core/backend/jax/numpy.py
keras_core/backend/numpy/numpy.py
keras_core/backend/tensorflow/numpy.py
keras_core/backend/torch/numpy.py
keras_core/ops/numpy.py
keras_core/ops/numpy_test.py
keras_core/ops/symbolic_arguments_test.py

Moved old branch to here due to cla isses

Keras tensor functions

---

keras_core/ops/numpy.py

Add some doctrings to `keras_core/ops/numpy.py`:
- absolute
- abs
- add
- all
- any
I will try to add more doctrings in subsequent PRs once I confirm their style (through this PR).

Add some docstrings to `keras_core/ops/numpy.py`

---

examples/keras_io/vision/keypoint_detection.py

**NOTE**: This example needs to fill out a Google Form for data
Update imports
Needed to initialize super class in keras.utils.Sequence subclass.
[Colab Notebook](https://colab.research.google.com/drive/1mfLUJfo5tIuYuQtQPN0h23EY3aSi8YK8?usp=sharing)
[keypoint_detection_keras.diff.txt](https://github.com/keras-team/keras-core/files/12098661/keypoint_detection_keras.diff.txt)

Port Keypoint detection to backend agnostic-keras-core

---

keras_core/layers/preprocessing/random_flip.py
keras_core/layers/preprocessing/random_flip_test.py
keras_core/ops/numpy.py

For the RandomFlip layer
- removed the direct tf dependency
- made it inherits from TFDataLayer

Make random flip backend agnostic

---

keras_core/ops/numpy.py

Do i also need to add the shape parameter in output of the examples. I tried running it in google collab but it doesn't show shape in output

doc: DocString for numpy.amax

---

examples/keras_io/tensorflow/vision/cutmix.py

Converted the keras-io example [CutMix data augmentation for image classification](https://keras.io/examples/vision/cutmix/) to `keras-core`.
[Colab Notebook link](https://colab.research.google.com/drive/1EwPk-5E38A5460RHbLOMo6HDZv5aOVwZ?usp=sharing)

Converted cutmix example to Keras Core

---

keras_core/backend/tensorflow/numpy.py
keras_core/backend/torch/numpy.py
keras_core/ops/numpy_test.py

This is more consistency follows up to the changes we started marking on #552.

Fix more spots torch != numpy for reductions

---

keras_core/backend/jax/core.py
keras_core/backend/tensorflow/core.py
keras_core/ops/core.py
keras_core/ops/core_test.py

Export ops.cond

---

keras_core/layers/layer.py

It saves ~10ms for forward pass. Tested on ResNet50.

Cache self.call() signature

---

keras_core/layers/layer.py
keras_core/ops/symbolic_arguments.py

It saves around ~5ms/step in ResNet.

Avoid some tree operations

---

examples/keras_io/tensorflow/vision/visualizing_what_convnets_learn.py

[Colab Notebook](https://colab.research.google.com/drive/1SQzD78XTtpoJoBDKH14jY54RXrQOn37Y?usp=sharing)

Port visualizing what convnets learn

---

examples/keras_io/vision/image_classifier.py

This PR is a follow-up for #608 addressing [this review comment](https://github.com/keras-team/keras-core/pull/608#discussion_r1275181964):
> I think at minima we should:
> 
> * drop the dependency on `tf.keras.Sequential` and just use a list or Augmenter
> * drop the dependency on `tf.one_hot`. You can use a `CategoryEncoding` layer for that
> * remove the tf.cast to float (unnecessary)
> * remove `import tensorflow` and do `from tensorflow import data as tf_data`
`keras_core.layers.CategoryEncoding` expects the labels to be `int32` but later in the pipeline `keras_cv.layers.CutMix` and `keras_cv.layers.MixUp` expect the labels to be `float32`. So, tensorflow is required for casting the labels to the correct data type depending on the layer they are input to. We can later remove this …

Fix the `ImageClassifier` demo and minimize the use of tensorflow

---

keras_core/layers/attention/multi_head_attention.py

With this change it slightly improve the performance of BERT with torch backend.

Performance improvement for MHA

---

requirements.txt

Minor corrections for `requirements.txt` to use all CPU requirements.
To use GPUs, one should install `requirements-cuda.txt`.

update requirements for all cpu install

---

examples/keras_io/vision/object_detection_using_vision_transformer.py

Backend-agnostic port of the example [Object detection with Vision Transformers](https://keras.io/examples/vision/object_detection_using_vision_transformer) that works with TF, Jax, and Torch backends. Based on the TF-compatible port originally contributed by @grasskin as part of https://github.com/keras-team/keras-core/pull/313.
Colab Notebook: https://colab.research.google.com/drive/1-HUon9woz5yag7rVtOYbsLnwPX3pbZCW?usp=sharing

Backend agnostic port of object detection using vit

---

keras_core/ops/nn.py

This PR completes the docstrings of activations available under `ops.nn.py`

Add activation docstrings // ops.nn.py

---

keras_core/ops/math_test.py

This PR removes tensorflow operations and hard-codes the expected values when possible.
It's not `tf.keras` and was not mentioned in the pinned request, but might be something useful?

Remove tf dependency from math_test

---

keras_core/backend/config.py
keras_core/backend/exports.py

This PR fixes some of the docstrings in `config.py` and improves the error message in `export.py`

Little cleanup in backend - config.py / export.py

---

keras_core/backend/jax/math.py
keras_core/backend/tensorflow/math.py
keras_core/backend/torch/math.py
keras_core/ops/math.py
keras_core/ops/math_test.py

Add rsqrt  to ops API

---

keras_core/layers/normalization/layer_normalization_test.py
keras_core/ops/math.py
keras_core/ops/operation_utils.py
keras_core/ops/operation_utils_test.py

The PR also contain some minor style fixes.

Support keras.Input in get_source_inputs

---

keras_core/layers/normalization/layer_normalization.py
keras_core/layers/normalization/layer_normalization_test.py

Add `rms_scaling` in LayerNormalization

---

keras_core/backend/numpy/image.py
keras_core/backend/numpy/nn.py
keras_core/legacy/preprocessing/image.py

We can now apply the new LazyModule of `scipy` to the codebase

Apply `scipy` LazyModule

---

keras_core/ops/numpy.py

Add Examples to some of numpy.py functions.

Add Examples to numpy.py functions 

---

examples/keras_io/generative/text_generation_gpt.py

1. colab [notebook](https://colab.research.google.com/drive/14AfveK03d7gjthwskcIHVHQIY-iDM_W5?usp=sharing)
2. diff 6349215
- keras -> keras_core
- tf.data/tf.strings -> tf_data/tf_strings
- tested with TensorFlow, JAX, and PyTorch backends

Convert  "GPT text generation from scratch with KerasNLP" to keras-core

---

keras_core/distribute/distribution.py
keras_core/distribution/distribution_lib.py

1. Added functions/classes based on the discussions with @fchollet.
2. All the docstring are populated.
3. All the implementation are not filled and will be done as followup.
I skip the Device class for now since there is not usages for it at the moment (which is also just a string wrapper.)

Add skeleton for the common distribution backend. 

---

keras_core/legacy/saving/legacy_h5_format_test.py
keras_core/legacy/saving/saving_utils.py

This PR extends backwards compatibility tests for the HDF5 format and adds backwards support for Lambdas.

Add more H5 backwards compatibility tests and lambda support

---

keras_core/activations/activations_test.py

This PR introduces improved tests for several activation functions, ensuring their robustness and precision:
These enhancements ensure that the activation functions behave as expected across various scenarios, contributing to the reliability and stability of the Keras-core.
`Leaky ReLU`: Added tests for various negative_slope values.
`ReLU6`: Enhanced tests to cover edge cases.
`SiLU/Swish`: Introduced tests for the activation function.
`GELU`: Added separate tests for approximate values, both True and False.
`Hard Sigmoid`: Extended the test to include more scenarios, ensuring better coverage.
`Sigmoid`: Improved test to cover a wider range of input values.
`SoftSign`: Adjusted the test for increased reliability.
`Softplus`: Extended the existing test for better coverage.
`Exponential`: …

Increase-test-coverage-in-activations_test.py

---

examples/keras_io/nlp/pretraining_BERT.py

Training is slow even in GPU environment is it usual or I'm missing something, tried with different backends still the training time remains constant

Convert pretraining_BERT.py example to keras core

---

keras_core/metrics/confusion_metrics_test.py

Fix formatting on unformatted file.

Format confusion_metrics_test

---

keras_core/saving/serialization_lib_test.py

Just stumbled across this, we had a test that didn't have `test_` in the name, was never run, and was very broken if you tried to run it.

Fix weird broken test that never ran

---

.github/workflows/actions.yml
.gitignore
codecov.yml
pyproject.toml

Enables codecoverage collection while running tests and uploads to codecov.io

Enable codecov

---

examples/keras_io/tensorflow/nlp/end_to_end_mlm_with_bert.py
keras_core/initializers/constant_initializers.py

As mentioned in #837, this PR provides a fix for `Constant` initializer. I believe there's no need to use `ops.cast()` as it applies the `standard_dtype` in `call()`.
This issue was found while trying to import [End-to-End Masked Language Modelling with BERT](https://keras.io/examples/nlp/masked_language_modeling/) to keras-core. The following changes are made:
- Fixed Imports
- Supports tensorflow backend
- Removed MaskedTextGenerator as it wasn't used anywhere, rather to display examples.
kindly take a look at the PR, and suggest changes, if and where necessary.
Here's the [diff](https://github.com/keras-team/keras-core/files/12540498/mlm_bert_port_diff.txt):
```diff
diff --git a/./keras-io/examples/nlp/masked_language_modeling.py …
```

bert-mlm port to keras-core with tf backend

---

README.md

Since code coverage has been enabled on this repo, I figured the work isn't complete until we display this badge.

Add test,codecov,pypi status badges to README

---

keras_core/backend/config.py
keras_core/utils/file_utils.py

Let me know if we want a test for this somehow, we don't really have test coverage for config.py or keras.json right now.

Respect the $KERAS_HOME environment variable for get_file
